import {
  Opportunity,
  StudentProfile,
  TargetRoleGapData,
  RoadmapStep,
  GapClosingResource,
  Application,
  NotificationItem,
} from '../types';

export const mockProfile: StudentProfile = {
  name: 'Alex Morgan',
  avatarUrl: 'https://ui-avatars.com/api/?name=Alex+Morgan&background=0284c7&color=fff&size=128&bold=true',
  degree: 'B.Tech / B.E.',
  major: 'Computer Science',
  year: '3rd Year',
  university: 'National Institute of Technology',
  gpa: 3.82,
  graduationDate: 'May 2027',
  verifiedProfilePercent: 94,
  profileStrength: 82,
  matchConfidence: 95,
  targetRole: 'Machine Learning Engineer',
  summary: 'Undergraduate CS student passionate about machine learning, distributed inference, and foundational vision-language models. Demonstrated project experience with PyTorch, automated ML pipelines, and SQL data wrangling.',
  skills: [
    { name: 'Python', level: 'Advanced (95%)', verified: true, verifiedVia: 'GitHub Repo NeuralClassifier', category: 'Languages' },
    { name: 'Machine Learning', level: 'Intermediate', verified: true, verifiedVia: 'Coursework CS421 (Grade A)', category: 'Core CS' },
    { name: 'SQL', level: 'Intermediate', verified: true, verifiedVia: 'Proctored Skill Assessment', category: 'Languages' },
    { name: 'TensorFlow / PyTorch', level: 'Intermediate', verified: true, verifiedVia: 'Project VisionTransformer-PyTorch', category: 'Frameworks' },
    { name: 'FastAPI', level: 'Intermediate', verified: true, verifiedVia: 'Project API Inference Gateway', category: 'Frameworks' },
    { name: 'Pandas & NumPy', level: 'Proficient', verified: true, verifiedVia: 'Kaggle Competition Medal', category: 'Frameworks' },
    { name: 'Git & GitHub', level: 'Advanced', verified: true, verifiedVia: 'Verified Commit History', category: 'Cloud & Tools' },
    { name: 'Data Structures & Algorithms', level: 'Advanced', verified: true, verifiedVia: 'Semester 3 Grade A', category: 'Core CS' },
    { name: 'Docker', level: 'Learning (20%)', verified: false, verifiedVia: 'Unverified', category: 'Cloud & Tools' },
    { name: 'AWS Cloud', level: 'Beginner (15%)', verified: false, verifiedVia: 'Unverified', category: 'Cloud & Tools' },
  ],
  education: [
    {
      institution: 'National Institute of Technology',
      degree: 'Bachelor of Technology in Computer Science',
      period: '2023 - 2027 (Expected)',
      gpa: '3.82 / 4.00 (Ranked top 5%)',
      courses: ['CS421: Machine Learning Systems', 'CS301: Data Structures & Algorithms', 'CS312: Database Management Systems', 'MATH220: Linear Algebra & Probability'],
    },
  ],
  projects: [
    {
      name: 'NeuralClassifier: Distributed ResNet Evaluation',
      description: 'Engineered an automated inference benchmarking suite comparing FP16 vs INT8 quantization latencies on edge devices.',
      technologies: ['Python', 'PyTorch', 'ONNX', 'FastAPI'],
      link: 'https://github.com/alexmorgan/neural-classifier',
      verified: true,
    },
    {
      name: 'VisionTransformer-PyTorch',
      description: 'Implemented ViT architecture from scratch for multi-class satellite imagery classification achieving 92.4% validation accuracy.',
      technologies: ['PyTorch', 'Torchvision', 'Pandas', 'WandB'],
      link: 'https://github.com/alexmorgan/vit-pytorch',
      verified: true,
    },
  ],
  certifications: [
    {
      name: 'Deep Learning Specialization',
      issuer: 'DeepLearning.AI',
      date: 'Aug 2025',
      verified: true,
    },
    {
      name: 'Verified Python Software Developer',
      issuer: 'SkillMatch Proctor Certification',
      date: 'Jan 2026',
      verified: true,
    },
  ],
};

export const mockOpportunities: Opportunity[] = [
  {
    id: 'opp-1',
    title: 'Machine Learning Intern',
    organization: 'TechNova Labs',
    organizationLogoText: 'TN',
    organizationSubtext: 'San Francisco / Remote',
    category: 'internships',
    categoryLabel: 'Internship',
    domain: 'AI / Machine Learning',
    location: 'San Francisco, CA (Remote Eligible)',
    mode: 'Remote',
    compensation: '$4,500 / month',
    deadline: '15 Oct 2026',
    deadlineDaysRemaining: 12,
    postedAgo: 'Posted 3 days ago',
    duration: '6 Months (Summer/Spring)',
    cohortSize: '4 Positions Open',
    description: 'At TechNova Labs, our Machine Learning Interns tackle real-world foundation model validation and automated inference optimization. You will embed directly into our Applied Intelligence Group, partnering closely with Senior Research Scientists and MLOps Architects to engineer the next generation of scalable evaluation harnesses.',
    keyResponsibilities: [
      'Design and implement automated model evaluation pipelines to benchmark task-specific parameter-efficient fine-tuning (PEFT) on open-source LLMs.',
      'Synthesize high-dimensional latency vs. accuracy Pareto curves for edge and serverless inference architectures.',
      'Curate, deduplicate, and validate multi-modal benchmark datasets utilizing specialized data wrangling tooling.',
      'Publish technical documentation and co-author internal findings for potential open-source tooling release.',
    ],
    requirements: {
      technicalSkills: [
        { name: 'Python', level: 'Advanced', matched: true, verificationSource: 'GitHub repo NeuralClassifier' },
        { name: 'Machine Learning', level: 'Intermediate', matched: true, verificationSource: 'Coursework CS421 (Grade A)' },
        { name: 'SQL', level: 'Intermediate', matched: true, verificationSource: 'Proctored Skill Assessment' },
        { name: 'TensorFlow / PyTorch', level: 'Intermediate', matched: true, verificationSource: 'Project VisionTransformer-PyTorch' },
        { name: 'Docker & Containerization', level: 'Essential', matched: false, gap: true, verificationSource: 'Missing' },
      ],
      academicCriteria: [
        'Enrolled in B.E. / B.Tech or M.S. in Computer Science, Data Science, AI/ML, or related quantitative discipline.',
        'Expected graduation window: 2027 or 2028.',
        'Demonstrated prior relevant project work or formal coursework in Machine Learning fundamentals.',
      ],
    },
    stages: [
      { step: 1, name: 'Profile Screen', description: 'Automated skill verification & resume match evaluation', completed: true },
      { step: 2, name: 'Tech Assessment', description: '90-min practical Python, PyTorch & data wrangling challenge', active: true },
      { step: 3, name: 'ML System Interview', description: 'Live collaborative review with Principal Research Scientist' },
      { step: 4, name: 'Offer & Matching', description: 'Placement confirmation and team allocation' },
    ],
    matchScore: 94,
    matchBreakdown: {
      skillsScore: 40,
      skillsTotal: 40,
      educationScore: 20,
      educationTotal: 20,
      interestsScore: 18,
      interestsTotal: 20,
      experienceScore: 16,
      experienceTotal: 20,
      skillsFitPercent: 98,
      academicCriteriaPercent: 100,
      experienceLevelPercent: 85,
    },
    matchedSkills: ['Python', 'Machine Learning', 'SQL', 'TensorFlow'],
    missingSkills: ['Docker'],
    verified: true,
    eligibilityStatus: 'Eligible',
    eligibilityNote: 'Eligible (B.Tech CS / 3rd Year • Min GPA 3.5 • Your GPA: 3.82)',
    verifiedBy: 'Verified by TechNova Talent Team',
    featured: true,
    imageBanner: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCala1I9OOiT4A9L5d9b3yvwj-p3GU81LIOJNCVPwJ6vXLm9XUVv2qIDQDFTlv6F8TUz7K_8A6KBS5LSITpGBA6cjcJS1cDiQduElsk8Ojz7xqTm5g88iwtkKjdGTQBMy84HuteU4LhIlI_pzT404V8cVKhyqt0CMFJvcaO32yXyB_CylnzCpf6gQPNHDsv5_nxgtyf3al2XXJQxZg3SlwYSBMjbL8ACnMsx9qWW7ptaD2F4zSwHOO8hg',
  },
  {
    id: 'opp-2',
    title: 'National AI Hackathon 2026',
    organization: 'InnovateAI & IEEE',
    organizationLogoText: 'IA',
    organizationSubtext: 'Online & Mumbai',
    category: 'hackathons',
    categoryLabel: 'Hackathon',
    domain: 'AI / Machine Learning',
    location: 'Hybrid / Online & Mumbai Center',
    mode: 'Hybrid',
    compensation: '$15,000 Grand Prize Pool',
    deadline: '22 Sep 2026',
    deadlineDaysRemaining: 4,
    postedAgo: 'Posted 5 days ago',
    duration: '48-Hour Sprint',
    cohortSize: '150 Student Teams',
    description: 'Build breakthrough generative AI agents and autonomous reasoning systems to solve pressing sustainability and healthcare challenges. Top 10 teams present to venture capitalists and enterprise incubators.',
    keyResponsibilities: [
      'Architect full-stack AI applications with live frontend and backend agent orchestration.',
      'Deploy multi-agent workflows using open models and function-calling endpoints.',
      'Deliver working code repo with automated unit tests and a 3-minute video demonstration.',
    ],
    requirements: {
      technicalSkills: [
        { name: 'Python', level: 'Advanced', matched: true },
        { name: 'Generative AI', level: 'Intermediate', matched: true },
        { name: 'Problem Solving', level: 'Advanced', matched: true },
      ],
      academicCriteria: ['Open to all University Undergrads and Graduate students globally.'],
    },
    matchScore: 91,
    matchBreakdown: {
      skillsScore: 38,
      skillsTotal: 40,
      educationScore: 20,
      educationTotal: 20,
      interestsScore: 20,
      interestsTotal: 20,
      experienceScore: 18,
      experienceTotal: 20,
    },
    matchedSkills: ['Python', 'Generative AI', 'Problem Solving'],
    missingSkills: [],
    verified: true,
    eligibilityStatus: 'Eligible',
    eligibilityNote: 'Open to all University Undergrads',
    verifiedBy: 'IEEE Student Chapter',
    featured: true,
  },
  {
    id: 'opp-3',
    title: 'NextGen Engineering Merit Scholarship',
    organization: 'Apex Foundation',
    organizationLogoText: 'AF',
    organizationSubtext: 'Academic Grant',
    category: 'scholarships',
    categoryLabel: 'Scholarship',
    domain: 'Computer Science',
    location: 'Pan-National Academic Award',
    mode: 'Online',
    compensation: '$8,000 / Year Tuition Grant',
    deadline: '05 Nov 2026',
    deadlineDaysRemaining: 32,
    postedAgo: 'Posted 1 week ago',
    duration: 'Annual Renewable Grant',
    cohortSize: '25 Scholars',
    description: 'Prestigious merit-based academic fellowship honoring top quantitative undergraduate engineers demonstrating stellar academic performance and impactful open-source contributions.',
    keyResponsibilities: [
      'Maintain minimum cumulative GPA of 3.6 throughout academic calendar.',
      'Participate in quarterly mentoring roundtables with engineering leaders.',
      'Author a technical capstone report in penultimate semester.',
    ],
    requirements: {
      technicalSkills: [
        { name: 'Computer Science Fundamentals', level: 'Advanced', matched: true },
        { name: 'Research / Open Source', level: 'Intermediate', matched: true },
      ],
      academicCriteria: ['B.Tech / B.E. 3rd Year • Min GPA 3.5 (Your GPA: 3.82)'],
    },
    matchScore: 88,
    matchBreakdown: {
      skillsScore: 35,
      skillsTotal: 40,
      educationScore: 20,
      educationTotal: 20,
      interestsScore: 20,
      interestsTotal: 20,
      experienceScore: 14,
      experienceTotal: 20,
    },
    matchedSkills: ['Computer Science', 'Data Structures', 'Algorithms'],
    missingSkills: [],
    verified: true,
    eligibilityStatus: 'Eligible',
    eligibilityNote: 'B.Tech 3rd Year • Min GPA 3.5 (Your GPA: 3.82)',
    verifiedBy: 'Apex Foundation Council',
    featured: true,
  },
  {
    id: 'opp-4',
    title: 'Full-Stack Data Engineering Project',
    organization: 'OpenData Guild',
    organizationLogoText: 'OD',
    organizationSubtext: 'Collaborative Open Source',
    category: 'projects',
    categoryLabel: 'Projects',
    domain: 'Cloud & DevOps',
    location: 'Remote Open-Source Cohort',
    mode: 'Remote',
    compensation: 'Stipend & Certificate Included ($1,200)',
    deadline: '18 Oct 2026',
    deadlineDaysRemaining: 15,
    postedAgo: 'Posted 4 days ago',
    duration: '8 Weeks',
    cohortSize: '3 Contributor Seats Remaining',
    description: 'Join a curated open-source working group building distributed ingestion pipelines, streaming transforms with Apache Spark/Flink, and automated PostgreSQL schema indexing.',
    keyResponsibilities: [
      'Develop real-time streaming connectors for public financial and climate datasets.',
      'Write integration tests and maintain CI/CD pipelines on GitHub Actions.',
      'Document benchmark throughput and optimize query latencies.',
    ],
    requirements: {
      technicalSkills: [
        { name: 'SQL', level: 'Intermediate', matched: true },
        { name: 'Python', level: 'Advanced', matched: true },
        { name: 'AWS', level: 'Essential', matched: false, gap: true },
      ],
      academicCriteria: ['Prior programming experience and basic relational database understanding.'],
    },
    matchScore: 86,
    matchBreakdown: {
      skillsScore: 34,
      skillsTotal: 40,
      educationScore: 20,
      educationTotal: 20,
      interestsScore: 18,
      interestsTotal: 20,
      experienceScore: 14,
      experienceTotal: 20,
    },
    matchedSkills: ['SQL', 'Python'],
    missingSkills: ['AWS'],
    verified: true,
    eligibilityStatus: 'Eligible',
    eligibilityNote: '3 Contributor Seats Remaining • Verification Required',
    verifiedBy: 'OpenData Foundation',
  },
  {
    id: 'opp-5',
    title: 'Cloud Architecture Apprenticeship',
    organization: 'CloudScale',
    organizationLogoText: 'CS',
    organizationSubtext: 'Flexible / Remote',
    category: 'skill-opportunities',
    categoryLabel: 'Skill Opportunity',
    domain: 'Cloud & DevOps',
    location: 'Flexible / Remote',
    mode: 'Flexible / Remote',
    compensation: 'Free Certification + $2,000 Milestone Bonus',
    deadline: '28 Oct 2026',
    deadlineDaysRemaining: 25,
    postedAgo: 'Posted 2 days ago',
    duration: '10 Weeks Structured Track',
    cohortSize: '40 Apprentices',
    description: 'Intensive apprentice track designed to bridge university CS knowledge with production cloud architecture. Includes sponsored AWS Solutions Architect exam voucher and direct interview pipeline.',
    keyResponsibilities: [
      'Deploy multi-region serverless APIs on AWS Lambda and API Gateway.',
      'Configure VPC peering, IAM role boundaries, and zero-trust security postures.',
      'Complete 4 guided enterprise workload migration case studies.',
    ],
    requirements: {
      technicalSkills: [
        { name: 'AWS', level: 'Intermediate', matched: false, gap: true },
        { name: 'Python', level: 'Intermediate', matched: true },
        { name: 'Networking Basics', level: 'Intermediate', matched: true },
      ],
      academicCriteria: ['Enrolled university student in STEM discipline.'],
    },
    matchScore: 92,
    matchBreakdown: {
      skillsScore: 36,
      skillsTotal: 40,
      educationScore: 20,
      educationTotal: 20,
      interestsScore: 20,
      interestsTotal: 20,
      experienceScore: 16,
      experienceTotal: 20,
    },
    matchedSkills: ['Python', 'Networking Basics'],
    missingSkills: ['AWS'],
    verified: true,
    eligibilityStatus: 'Eligible',
    eligibilityNote: 'Sponsored AWS Examination Voucher Included',
    verifiedBy: 'CloudScale Academy',
  },
  {
    id: 'opp-6',
    title: 'Deep Learning Systems Specialization',
    organization: 'DeepLearning.AI',
    organizationLogoText: 'DL',
    organizationSubtext: 'Interactive Coursework',
    category: 'courses',
    categoryLabel: 'Courses',
    domain: 'AI / Machine Learning',
    location: 'Online / Self-Paced',
    mode: 'Online',
    compensation: 'Free Student Access ($390 value)',
    deadline: '30 Nov 2026',
    deadlineDaysRemaining: 58,
    postedAgo: 'Posted 6 days ago',
    duration: '4-Course Series',
    cohortSize: 'Open Enrollment',
    description: 'Master convolutional networks, transformers, sequence models, and distributed training techniques with Andrew Ng and leading researchers. Auto-indexed directly into your SkillMatch profile upon completion.',
    keyResponsibilities: [
      'Build and train neural network architectures with PyTorch and NumPy.',
      'Optimize hyperparameters and debug gradient explosion / vanishing.',
      'Deploy production NLP models on huggingface transformers.',
    ],
    requirements: {
      technicalSkills: [
        { name: 'Python', level: 'Intermediate', matched: true },
        { name: 'Linear Algebra', level: 'Basic', matched: true },
      ],
      academicCriteria: ['Foundational programming skills.'],
    },
    matchScore: 95,
    matchBreakdown: {
      skillsScore: 40,
      skillsTotal: 40,
      educationScore: 20,
      educationTotal: 20,
      interestsScore: 20,
      interestsTotal: 20,
      experienceScore: 15,
      experienceTotal: 20,
    },
    matchedSkills: ['Python', 'Linear Algebra', 'Machine Learning'],
    missingSkills: [],
    verified: true,
    eligibilityStatus: 'Eligible',
    eligibilityNote: 'Free Academic Grant Voucher',
    verifiedBy: 'DeepLearning.AI Partner',
  },
  {
    id: 'opp-7',
    title: 'Associate Software Engineer (Graduate 2027)',
    organization: 'Stripe',
    organizationLogoText: 'ST',
    organizationSubtext: 'San Francisco / Seattle / Dublin',
    category: 'jobs',
    categoryLabel: 'Jobs',
    domain: 'Full-Stack Web',
    location: 'San Francisco, CA / Hybrid',
    mode: 'Hybrid',
    compensation: '$145,000 - $175,000 Base + Equity',
    deadline: '10 Dec 2026',
    deadlineDaysRemaining: 68,
    postedAgo: 'Posted 1 week ago',
    duration: 'Full-Time Employment',
    cohortSize: 'Campus Graduate Intake',
    description: 'Help build economic infrastructure for the internet. Work on core payments, global billing engines, financial graph databases, and developer-first APIs trusted by millions of businesses worldwide.',
    keyResponsibilities: [
      'Build robust, fault-tolerant backend services in Ruby, Java, and Go.',
      'Design high-throughput distributed database transactions with strict ACID guarantees.',
      'Collaborate with product designers to ship intuitive merchant interfaces.',
    ],
    requirements: {
      technicalSkills: [
        { name: 'Algorithms & Data Structures', level: 'Advanced', matched: true },
        { name: 'System Design', level: 'Intermediate', matched: true },
        { name: 'Distributed Systems', level: 'Intermediate', matched: false, gap: true },
      ],
      academicCriteria: ['Bachelor’s degree in Computer Science graduating by June 2027.'],
    },
    matchScore: 84,
    matchBreakdown: {
      skillsScore: 32,
      skillsTotal: 40,
      educationScore: 20,
      educationTotal: 20,
      interestsScore: 18,
      interestsTotal: 20,
      experienceScore: 14,
      experienceTotal: 20,
    },
    matchedSkills: ['Algorithms', 'Data Structures', 'Python', 'SQL'],
    missingSkills: ['Distributed Systems'],
    verified: true,
    eligibilityStatus: 'Eligible',
    eligibilityNote: 'Campus Placement Fast-Track Verified',
    verifiedBy: 'Stripe University Recruiting',
  },
  {
    id: 'opp-8',
    title: 'Distributed Systems & ML Acceleration Internship',
    organization: 'NVIDIA Research',
    organizationLogoText: 'NV',
    organizationSubtext: 'Santa Clara / Remote',
    category: 'internships',
    categoryLabel: 'Internship',
    domain: 'AI / Machine Learning',
    location: 'Santa Clara, CA (Hybrid / Remote)',
    mode: 'Hybrid',
    compensation: '$6,200 / month',
    deadline: '20 Oct 2026',
    deadlineDaysRemaining: 17,
    postedAgo: 'Posted 3 days ago',
    duration: '12-16 Weeks',
    cohortSize: '6 Positions',
    description: 'Work alongside leading GPU computing scientists to optimize TensorRT inference engines and CUDA kernels for massive multimodal transformer architectures.',
    keyResponsibilities: [
      'Profile CUDA kernel bottlenecks using Nsight Compute.',
      'Optimize tensor memory layouts and FP8 / FP4 precision pipelines.',
      'Contribute to open-source vLLM and TensorRT-LLM frameworks.',
    ],
    requirements: {
      technicalSkills: [
        { name: 'C++ / CUDA', level: 'Intermediate', matched: false, gap: true },
        { name: 'Python', level: 'Advanced', matched: true },
        { name: 'PyTorch Internals', level: 'Intermediate', matched: true },
      ],
      academicCriteria: ['Enrolled in CS / Electrical Engineering degree with strong systems background.'],
    },
    matchScore: 81,
    matchBreakdown: {
      skillsScore: 30,
      skillsTotal: 40,
      educationScore: 20,
      educationTotal: 20,
      interestsScore: 19,
      interestsTotal: 20,
      experienceScore: 12,
      experienceTotal: 20,
    },
    matchedSkills: ['Python', 'PyTorch Internals'],
    missingSkills: ['C++ / CUDA'],
    verified: true,
    eligibilityStatus: 'Partially Eligible',
    eligibilityNote: 'Partially Eligible (Needs C++ / CUDA Verification)',
    verifiedBy: 'NVIDIA University Programs',
  },
];

export const mockTargetRoleData: TargetRoleGapData = {
  roleId: 'role-ml-eng',
  roleTitle: 'Machine Learning Engineer',
  readinessScore: 78,
  estimatedWeeksToClose: '3–4 weeks',
  competenciesMet: 14,
  competenciesTotal: 18,
  mastered: [
    {
      name: 'Python Architecture',
      level: '95% Advanced',
      description: 'Algorithmic complexity, OOP, multiprocessing',
      verificationNote: 'Verified via SkillMatch Proctor',
    },
    {
      name: 'ML Algorithms',
      level: 'Intermediate',
      description: 'Random Forests, Gradient Boosting, SVMs',
      verificationNote: 'Course verified • Stanford CS229 equiv.',
    },
    {
      name: 'SQL & Relational Schemas',
      level: 'Intermediate',
      description: 'Complex window functions, CTEs, indexing',
      verificationNote: 'Verified via LeetCode DB track',
    },
    {
      name: 'Pandas & Data Profiling',
      level: 'Proficient',
      description: 'Feature engineering, ETL transforms, Seaborn',
      verificationNote: '2 Published Kaggle Notebooks',
    },
  ],
  developing: [
    {
      name: 'Deep Learning & PyTorch',
      level: '68% Progress',
      description: 'Backpropagation, CNN architectures, PyTorch Lightning',
      verificationNote: 'Active course enrollment (Finish in 12 days)',
      progressPercent: 68,
    },
    {
      name: 'FastAPI Serving',
      level: '1 Project',
      description: 'Async model inference, Pydantic validation',
      verificationNote: 'Project codebase logged',
      progressPercent: 45,
    },
    {
      name: 'Linear Algebra & Calculus',
      level: 'Sem 4 Completed',
      description: 'Eigenvalues, SVD matrix decomposition',
      verificationNote: 'University transcript validated',
      progressPercent: 85,
    },
  ],
  criticalGaps: [
    {
      name: 'Docker & Containerization',
      level: 'Critical Gap',
      description: 'Multi-stage builds, GPU passthrough with NVIDIA toolkit',
      verificationNote: 'No verified artifacts submitted',
      rolesDemandPercent: 85,
      priority: 'High',
    },
    {
      name: 'AWS Cloud Deployments',
      level: 'Critical Gap',
      description: 'EC2 spot instances, S3 pipelines, SageMaker training',
      verificationNote: 'Missing practical deployment proof',
      rolesDemandPercent: 72,
      priority: 'High',
    },
    {
      name: 'MLOps & Model Observability',
      level: 'Critical Gap',
      description: 'MLflow tracking, data drift monitoring, CI/CD',
      verificationNote: 'Zero logged repos with pipeline tests',
      rolesDemandPercent: 64,
      priority: 'High',
    },
  ],
  employerBenchmarks: [
    {
      company: 'TechNova AI',
      tier: 'Tier 1',
      role: 'ML Engineering Intern (Fall 2026)',
      matchScore: 82,
      statusNote: 'Missing Docker & SageMaker',
      isStrongFit: false,
    },
    {
      company: 'Scale Labs',
      tier: 'Growth',
      role: 'Data & Applied ML Intern',
      matchScore: 88,
      statusNote: 'Strong Python/SQL fit',
      isStrongFit: true,
    },
    {
      company: 'Datadog',
      tier: 'Enterprise',
      role: 'AI Systems & Observability',
      matchScore: 64,
      statusNote: 'Requires MLOps tooling',
      isStrongFit: false,
    },
  ],
};

export const mockRoadmapSteps: RoadmapStep[] = [
  {
    id: 'step-1',
    stepNumber: 1,
    title: 'Step 1: Python & Data Structures',
    status: 'completed',
    statusLabel: 'Completed',
    description: 'Foundational fluency with algorithms, time complexity, and memory management.',
    tag: 'Semester 3 • Grade: A',
    meta: 'Grade A',
  },
  {
    id: 'step-2',
    stepNumber: 2,
    title: 'Step 2: Statistics & Applied Probability',
    status: 'completed',
    statusLabel: 'Completed',
    description: 'Bayesian inference, hypothesis testing, stochastic processes, and regression.',
    tag: 'Semester 3 • Grade: A',
    meta: 'Grade A',
  },
  {
    id: 'step-3',
    stepNumber: 3,
    title: 'Step 3: Classical Machine Learning & Scikit-Learn',
    status: 'completed',
    statusLabel: 'Completed',
    description: 'Dimensionality reduction (PCA), clustering, ensembles, cross-validation tuning.',
    tag: '2 Production Repos',
    meta: '2 Repos Verified',
  },
  {
    id: 'step-4',
    stepNumber: 4,
    title: 'Step 4: Deep Learning & Frameworks',
    status: 'current',
    statusLabel: 'Current Focus',
    description: 'Transformer architectures, attention mechanisms, transfer learning with HuggingFace.',
    tag: 'Active Enrollment',
    meta: 'Finish in 12 days',
    badge: 'Active Focus',
  },
  {
    id: 'step-5',
    stepNumber: 5,
    title: 'Step 5: Docker & Containerized Environments',
    status: 'upcoming',
    statusLabel: 'Upcoming Action',
    description: 'Creating lightweight Python runtime images, GPU binding, and reproducible evaluation harnesses.',
    tag: '12-hour micro-track',
    meta: 'Target: +6% Match Boost',
  },
  {
    id: 'step-6',
    stepNumber: 6,
    title: 'Step 6: Cloud Deployment on AWS / GCP',
    status: 'upcoming',
    statusLabel: 'Upcoming',
    description: 'Serverless endpoints, Lambda model triggers, S3 storage tiers, and billing guardrails.',
    tag: 'Estimated 3 weeks',
    meta: 'AWS Skill Builder',
  },
  {
    id: 'step-7',
    stepNumber: 7,
    title: 'Step 7: Portfolio Capstone Project: End-to-End LLM App',
    status: 'upcoming',
    statusLabel: 'Milestone Target',
    description: 'Deploy fine-tuned small language model with RAG vector search, Dockerized on AWS EC2.',
    tag: 'Portfolio Verified',
    meta: 'Capstone Submission',
  },
  {
    id: 'step-8',
    stepNumber: 8,
    title: 'Step 8: Summer ML Internship Placement',
    status: 'upcoming',
    statusLabel: 'Target Placement',
    description: 'Target matches: TechNova AI, Datadog Research, or Scale AI cohort.',
    tag: 'Oct 2026 Recruitment',
    meta: 'Target Tier 1',
  },
  {
    id: 'step-9',
    stepNumber: 9,
    title: 'Step 9: Junior ML Engineer Full-Time Launch',
    status: 'upcoming',
    statusLabel: 'Career Launch',
    description: 'Full-time compensation benchmark: $135k – $165k base + equity.',
    tag: 'Post-Graduation 2027',
    meta: 'Placement Goal',
  },
];

export const mockGapClosingResources: GapClosingResource[] = [
  {
    id: 'res-1',
    title: 'Docker for Data Scientists & ML Engineers',
    provider: 'DeepLearning.AI Short Course',
    type: 'Course',
    addressesGap: 'Docker',
    duration: '12 Hours • Free',
    impactScore: '98% Match Impact (+6% Boost)',
    description: 'Master container packaging, building reproducible PyTorch environments, and setting up Docker Compose test rigs.',
    perks: 'Includes 1 portfolio code submission',
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBrtIOPKnFD7Jp8aUITg6G431HcxQTXHt1zYYKEVuBSQ-lgpdawMD951_SFD6x7UabQu5Mql2SKXvLh9X-Prk8-ziPT0CodOHvkAjxEp_qwki7W6P-kuZ8kaGVLiSNxkbVCyso7oB44Gg9U-b76ynguV-yZdIV1S5kDh1mcnPcHgrSC_N8EU4TI5mbLSkBu0l6JZugkHiuDejyReeI7upP-T_pszZ7Qlg_gEKtydy4TE8TN4egkD-Nz0A',
  },
  {
    id: 'res-2',
    title: 'AWS Cloud Practitioner & SageMaker Basics',
    provider: 'AWS Skill Builder',
    type: 'Certification',
    addressesGap: 'AWS Cloud',
    duration: 'Free Tier Eligible',
    impactScore: '94% Match Impact (+5% Boost)',
    description: 'Configure AWS Identity access, launch EC2 instances for batch prediction, and mount data stores using S3 buckets.',
    perks: 'Free student credits included ($100)',
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBWK0LWygK67k1mBzrzNl0azLLnWjqnnTR5qxvftkyUfmjhZSwl1iX0jlWGT5j_b5LUOaK46hNkm2zM8hWGJ5zjmsakYMiEEfi4o8Kvyqn9knXCpNkQRT-LA9hJB-ihk8BP_kuk57b8s9a2RTi1qnMdciIEPPefvfA5Hr-WODeY7rMKaQUjbE_4uQGMHdcdI2BvidNebbLnoaOm5npBCotdTS_gf0cmXPv5R-OCvof1_SZtJr2-BmEXVA',
  },
  {
    id: 'res-3',
    title: 'End-to-End MLOps Pipeline with MLflow & CI/CD',
    provider: 'SkillMatch Guided Lab',
    type: 'Project',
    addressesGap: 'MLOps & CI/CD',
    duration: 'Self-Paced Project (15h)',
    impactScore: 'Closes 2 Gaps (+8% Boost)',
    description: 'Build an automated pipeline that ingests data, executes continuous model tests via GitHub Actions, and tracks experiments in MLflow.',
    perks: 'Auto-audited for your public portfolio',
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDrc45R5-dSqQdiz2Yr4Jir0BepoQiUIabXL-PWxnncDkRFlmbG6yysY2z3RaEM0RogR8k1t5Uyvt9QxLdAOfefrO5XnFDWIdFIvBIVNAteCKZGv-A5W6tci59KJ7ArwdtclaeZU4Hr0XyNR0VKmSA0M92QBa-reCM9tVv5HtWg04HXxzTCN4RD9C6MKB1B0W7chlrIkzQ4s9FfFW5Mb9nvJDlmKS-5ncaJFAmxzD0ygCqb5c15NMQXWQ',
  },
];

export const mockApplications: Application[] = [
  {
    id: 'app-1',
    opportunityId: 'opp-1',
    opportunityTitle: 'Machine Learning Intern',
    organization: 'TechNova Labs',
    category: 'internships',
    appliedDate: '12 Sep 2026',
    status: 'Technical Assessment',
    statusColor: 'bg-primary-container text-on-primary',
    currentStage: 'Stage 2: 90-min Coding & ML Systems Assessment',
    nextDeadline: 'Due 25 Sep 2026',
    matchScore: 94,
  },
  {
    id: 'app-2',
    opportunityId: 'opp-2',
    opportunityTitle: 'National AI Hackathon 2026',
    organization: 'InnovateAI & IEEE',
    category: 'hackathons',
    appliedDate: '10 Sep 2026',
    status: 'In Review',
    statusColor: 'bg-surface-container-highest text-primary',
    currentStage: 'Proposal Review by Technical Committee',
    nextDeadline: 'Results on 22 Sep 2026',
    matchScore: 91,
  },
  {
    id: 'app-3',
    opportunityId: 'opp-3',
    opportunityTitle: 'NextGen Engineering Merit Scholarship',
    organization: 'Apex Foundation',
    category: 'scholarships',
    appliedDate: '01 Sep 2026',
    status: 'In Review',
    statusColor: 'bg-surface-container-highest text-primary',
    currentStage: 'Transcript and Merit Verification',
    nextDeadline: 'Award Notification 05 Nov 2026',
    matchScore: 88,
  },
  {
    id: 'app-4',
    opportunityId: 'opp-4',
    opportunityTitle: 'Full-Stack Data Engineering Project',
    organization: 'OpenData Guild',
    category: 'projects',
    appliedDate: '08 Sep 2026',
    status: 'Interviewing',
    statusColor: 'bg-tertiary-container text-on-tertiary',
    currentStage: 'Open-Source Maintainer Sync (30 min)',
    nextDeadline: 'Interview scheduled Sep 24',
    matchScore: 86,
  },
  {
    id: 'app-5',
    opportunityId: 'opp-7',
    opportunityTitle: 'Associate Software Engineer (Graduate 2027)',
    organization: 'Stripe',
    category: 'jobs',
    appliedDate: '05 Sep 2026',
    status: 'Applied',
    statusColor: 'bg-surface-container-low text-on-surface-variant',
    currentStage: 'Application Received & Queued for Recruiter Review',
    nextDeadline: 'Expected update by Oct 10',
    matchScore: 84,
  },
];

export const mockNotifications: NotificationItem[] = [
  {
    id: 'notif-1',
    title: 'TechNova ML Internship Invitation',
    description: 'You have been invited to complete Stage 2: Technical Assessment for Machine Learning Intern.',
    timeAgo: '2 hours ago',
    read: false,
    type: 'application',
    link: '/opportunity/opp-1',
  },
  {
    id: 'notif-2',
    title: 'Approaching Deadline: InnovateAI Hackathon',
    description: 'Submission window closes in 4 days (Sep 22). Complete your team registration now.',
    timeAgo: '5 hours ago',
    read: false,
    type: 'deadline',
    link: '/opportunity/opp-2',
  },
  {
    id: 'notif-3',
    title: 'New High-Confidence Match: NVIDIA Research',
    description: 'A new role matching 81% of your verified skills has been posted in Internships.',
    timeAgo: '1 day ago',
    read: false,
    type: 'match',
    link: '/opportunity/opp-8',
  },
  {
    id: 'notif-4',
    title: 'Skill Verified: Python Proctor Assessment',
    description: 'Your Python proctored test score (95% Advanced) has been verified and added to your profile.',
    timeAgo: '2 days ago',
    read: true,
    type: 'system',
    link: '/profile',
  },
];
