"""opportunity_fields_enhancement

Revision ID: 4a3d711861a2
Revises: 63cb85d9d40f
Create Date: 2026-09-11 20:48:46.458050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a3d711861a2'
down_revision: Union[str, None] = '63cb85d9d40f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('opportunities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('required_skills', sa.JSON(), nullable=False))
        batch_op.add_column(sa.Column('preferred_skills', sa.JSON(), nullable=False))
        batch_op.add_column(sa.Column('eligibility_requirements', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('degree_requirements', sa.JSON(), nullable=False))
        batch_op.add_column(sa.Column('branch_requirements', sa.JSON(), nullable=False))
        batch_op.add_column(sa.Column('academic_year_requirements', sa.JSON(), nullable=False))
        batch_op.add_column(sa.Column('experience_requirements', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('application_url', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('opportunities', schema=None) as batch_op:
        batch_op.drop_column('application_url')
        batch_op.drop_column('experience_requirements')
        batch_op.drop_column('academic_year_requirements')
        batch_op.drop_column('branch_requirements')
        batch_op.drop_column('degree_requirements')
        batch_op.drop_column('eligibility_requirements')
        batch_op.drop_column('preferred_skills')
        batch_op.drop_column('required_skills')

    # ### end Alembic commands ###
