"""profile_and_skills_enhancements

Revision ID: 63cb85d9d40f
Revises: 8b4aace4afc7
Create Date: 2026-09-11 20:36:15.937908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63cb85d9d40f'
down_revision: Union[str, None] = '8b4aace4afc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('issuing_organization', sa.String(length=255), nullable=False))

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('skills', sa.JSON(), nullable=False))
        batch_op.add_column(sa.Column('project_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('github_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('start_date', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('end_date', sa.String(length=50), nullable=True))

    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.add_column(sa.Column('normalized_name', sa.String(length=100), nullable=False))
        batch_op.create_index(batch_op.f('ix_skills_normalized_name'), ['normalized_name'], unique=True)

    with op.batch_alter_table('student_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('college', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('branch', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('academic_year', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('graduation_year', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('preferred_domains', sa.JSON(), nullable=False))
        batch_op.add_column(sa.Column('preferred_locations', sa.JSON(), nullable=False))
        batch_op.add_column(sa.Column('preferred_work_mode', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('experience', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('bio', sa.Text(), nullable=True))

    with op.batch_alter_table('student_skills', schema=None) as batch_op:
        batch_op.add_column(sa.Column('proficiency', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('experience_level', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_skills', schema=None) as batch_op:
        batch_op.drop_column('experience_level')
        batch_op.drop_column('proficiency')

    with op.batch_alter_table('student_profiles', schema=None) as batch_op:
        batch_op.drop_column('bio')
        batch_op.drop_column('experience')
        batch_op.drop_column('preferred_work_mode')
        batch_op.drop_column('preferred_locations')
        batch_op.drop_column('preferred_domains')
        batch_op.drop_column('graduation_year')
        batch_op.drop_column('academic_year')
        batch_op.drop_column('branch')
        batch_op.drop_column('college')

    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_skills_normalized_name'))
        batch_op.drop_column('normalized_name')

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('end_date')
        batch_op.drop_column('start_date')
        batch_op.drop_column('github_url')
        batch_op.drop_column('project_url')
        batch_op.drop_column('skills')
        batch_op.drop_column('title')

    with op.batch_alter_table('certifications', schema=None) as batch_op:
        batch_op.drop_column('issuing_organization')

    # ### end Alembic commands ###
