"""initial_tables

Revision ID: 8b4aace4afc7
Revises: 
Create Date: 2026-09-11 20:31:23.587886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b4aace4afc7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('interests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_interests_name'), ['name'], unique=True)

    op.create_table('opportunities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('organization', sa.String(length=255), nullable=False),
    sa.Column('organization_logo_text', sa.String(length=10), nullable=False),
    sa.Column('organization_subtext', sa.String(length=255), nullable=True),
    sa.Column('category', sa.Enum('INTERNSHIP', 'HACKATHON', 'SCHOLARSHIP', 'COURSE', 'PROJECT', 'JOB', 'SKILL_OPPORTUNITY', name='opportunity_category'), nullable=False),
    sa.Column('category_label', sa.String(length=100), nullable=False),
    sa.Column('domain', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=150), nullable=False),
    sa.Column('mode', sa.Enum('REMOTE', 'HYBRID', 'ONSITE', 'ONLINE', 'FLEXIBLE', name='work_mode'), nullable=False),
    sa.Column('compensation', sa.String(length=100), nullable=True),
    sa.Column('deadline', sa.String(length=50), nullable=False),
    sa.Column('deadline_days_remaining', sa.Integer(), nullable=True),
    sa.Column('posted_ago', sa.String(length=50), nullable=False),
    sa.Column('duration', sa.String(length=100), nullable=True),
    sa.Column('cohort_size', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('key_responsibilities', sa.JSON(), nullable=False),
    sa.Column('requirements', sa.JSON(), nullable=False),
    sa.Column('stages', sa.JSON(), nullable=True),
    sa.Column('match_score', sa.Integer(), nullable=False),
    sa.Column('match_breakdown', sa.JSON(), nullable=False),
    sa.Column('matched_skills', sa.JSON(), nullable=False),
    sa.Column('missing_skills', sa.JSON(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('eligibility_status', sa.Enum('ELIGIBLE', 'PARTIALLY_ELIGIBLE', 'NOT_ELIGIBLE', name='eligibility_status'), nullable=False),
    sa.Column('eligibility_note', sa.String(length=255), nullable=False),
    sa.Column('verified_by', sa.String(length=150), nullable=True),
    sa.Column('featured', sa.Boolean(), nullable=False),
    sa.Column('image_banner', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('opportunities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_opportunities_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_opportunities_domain'), ['domain'], unique=False)
        batch_op.create_index(batch_op.f('ix_opportunities_location'), ['location'], unique=False)
        batch_op.create_index(batch_op.f('ix_opportunities_organization'), ['organization'], unique=False)
        batch_op.create_index(batch_op.f('ix_opportunities_title'), ['title'], unique=False)

    op.create_table('skills',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_skills_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_skills_name'), ['name'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('STUDENT', 'ADMIN', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('type', sa.Enum('MATCH', 'DEADLINE', 'APPLICATION', 'SYSTEM', name='notification_type'), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('link', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_is_read'), ['is_read'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)

    op.create_table('opportunity_skills',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('opportunity_id', sa.String(length=36), nullable=False),
    sa.Column('skill_id', sa.String(length=36), nullable=False),
    sa.Column('level', sa.Enum('BEGINNER', 'INTERMEDIATE', 'ADVANCED', 'ESSENTIAL', name='skill_level'), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('verification_source', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('opportunity_id', 'skill_id', name='uq_opportunity_skill')
    )
    with op.batch_alter_table('opportunity_skills', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_opportunity_skills_opportunity_id'), ['opportunity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_opportunity_skills_skill_id'), ['skill_id'], unique=False)

    op.create_table('saved_opportunities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('opportunity_id', sa.String(length=36), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'opportunity_id', name='uq_user_saved_opportunity')
    )
    with op.batch_alter_table('saved_opportunities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_saved_opportunities_opportunity_id'), ['opportunity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_saved_opportunities_user_id'), ['user_id'], unique=False)

    op.create_table('student_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('degree', sa.String(length=100), nullable=True),
    sa.Column('major', sa.String(length=100), nullable=True),
    sa.Column('year', sa.String(length=50), nullable=True),
    sa.Column('university', sa.String(length=200), nullable=True),
    sa.Column('gpa', sa.Float(), nullable=True),
    sa.Column('graduation_date', sa.String(length=50), nullable=True),
    sa.Column('verified_profile_percent', sa.Integer(), nullable=False),
    sa.Column('profile_strength', sa.Integer(), nullable=False),
    sa.Column('match_confidence', sa.Integer(), nullable=False),
    sa.Column('target_role', sa.String(length=100), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('student_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_student_profiles_user_id'), ['user_id'], unique=True)

    op.create_table('applications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('student_profile_id', sa.String(length=36), nullable=False),
    sa.Column('opportunity_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('SAVED', 'PLANNING', 'APPLIED', 'SHORTLISTED', 'INTERVIEW', 'SELECTED', 'REJECTED', name='application_status'), nullable=False),
    sa.Column('applied_date', sa.String(length=50), nullable=False),
    sa.Column('current_stage', sa.String(length=100), nullable=False),
    sa.Column('next_deadline', sa.String(length=50), nullable=True),
    sa.Column('match_score', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_profile_id'], ['student_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_profile_id', 'opportunity_id', name='uq_student_opportunity_application')
    )
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_applications_opportunity_id'), ['opportunity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_applications_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_applications_student_profile_id'), ['student_profile_id'], unique=False)

    op.create_table('certifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('student_profile_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('issuer', sa.String(length=255), nullable=False),
    sa.Column('issue_date', sa.String(length=50), nullable=True),
    sa.Column('credential_id', sa.String(length=255), nullable=True),
    sa.Column('credential_url', sa.String(length=500), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['student_profile_id'], ['student_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('certifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_certifications_student_profile_id'), ['student_profile_id'], unique=False)

    op.create_table('projects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('student_profile_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('technologies', sa.JSON(), nullable=False),
    sa.Column('link', sa.String(length=500), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['student_profile_id'], ['student_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_student_profile_id'), ['student_profile_id'], unique=False)

    op.create_table('recommendations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('student_profile_id', sa.String(length=36), nullable=False),
    sa.Column('opportunity_id', sa.String(length=36), nullable=False),
    sa.Column('match_score', sa.Integer(), nullable=False),
    sa.Column('match_reasons', sa.JSON(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_profile_id'], ['student_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_profile_id', 'opportunity_id', name='uq_student_opportunity_recommendation')
    )
    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recommendations_opportunity_id'), ['opportunity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recommendations_student_profile_id'), ['student_profile_id'], unique=False)

    op.create_table('skill_gaps',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('student_profile_id', sa.String(length=36), nullable=False),
    sa.Column('target_role', sa.String(length=150), nullable=False),
    sa.Column('readiness_score', sa.Integer(), nullable=False),
    sa.Column('estimated_weeks', sa.String(length=50), nullable=False),
    sa.Column('competencies_met', sa.Integer(), nullable=False),
    sa.Column('competencies_total', sa.Integer(), nullable=False),
    sa.Column('mastered_skills', sa.JSON(), nullable=False),
    sa.Column('developing_skills', sa.JSON(), nullable=False),
    sa.Column('critical_gaps', sa.JSON(), nullable=False),
    sa.Column('employer_benchmarks', sa.JSON(), nullable=False),
    sa.Column('roadmap_steps', sa.JSON(), nullable=False),
    sa.Column('gap_closing_resources', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['student_profile_id'], ['student_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('skill_gaps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_skill_gaps_student_profile_id'), ['student_profile_id'], unique=False)

    op.create_table('student_interests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('student_profile_id', sa.String(length=36), nullable=False),
    sa.Column('interest_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['interest_id'], ['interests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_profile_id'], ['student_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_profile_id', 'interest_id', name='uq_student_interest')
    )
    with op.batch_alter_table('student_interests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_student_interests_interest_id'), ['interest_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_interests_student_profile_id'), ['student_profile_id'], unique=False)

    op.create_table('student_skills',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('student_profile_id', sa.String(length=36), nullable=False),
    sa.Column('skill_id', sa.String(length=36), nullable=False),
    sa.Column('level', sa.Enum('BEGINNER', 'INTERMEDIATE', 'ADVANCED', 'ESSENTIAL', name='skill_level'), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('verified_via', sa.String(length=200), nullable=True),
    sa.Column('progress_percent', sa.Integer(), nullable=False),
    sa.Column('priority', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_profile_id'], ['student_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_profile_id', 'skill_id', name='uq_student_skill')
    )
    with op.batch_alter_table('student_skills', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_student_skills_skill_id'), ['skill_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_skills_student_profile_id'), ['student_profile_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_skills', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_skills_student_profile_id'))
        batch_op.drop_index(batch_op.f('ix_student_skills_skill_id'))

    op.drop_table('student_skills')
    with op.batch_alter_table('student_interests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_interests_student_profile_id'))
        batch_op.drop_index(batch_op.f('ix_student_interests_interest_id'))

    op.drop_table('student_interests')
    with op.batch_alter_table('skill_gaps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_skill_gaps_student_profile_id'))

    op.drop_table('skill_gaps')
    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recommendations_student_profile_id'))
        batch_op.drop_index(batch_op.f('ix_recommendations_opportunity_id'))

    op.drop_table('recommendations')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_student_profile_id'))

    op.drop_table('projects')
    with op.batch_alter_table('certifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_certifications_student_profile_id'))

    op.drop_table('certifications')
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_applications_student_profile_id'))
        batch_op.drop_index(batch_op.f('ix_applications_status'))
        batch_op.drop_index(batch_op.f('ix_applications_opportunity_id'))

    op.drop_table('applications')
    with op.batch_alter_table('student_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_profiles_user_id'))

    op.drop_table('student_profiles')
    with op.batch_alter_table('saved_opportunities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_saved_opportunities_user_id'))
        batch_op.drop_index(batch_op.f('ix_saved_opportunities_opportunity_id'))

    op.drop_table('saved_opportunities')
    with op.batch_alter_table('opportunity_skills', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_opportunity_skills_skill_id'))
        batch_op.drop_index(batch_op.f('ix_opportunity_skills_opportunity_id'))

    op.drop_table('opportunity_skills')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_is_read'))

    op.drop_table('notifications')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_skills_name'))
        batch_op.drop_index(batch_op.f('ix_skills_category'))

    op.drop_table('skills')
    with op.batch_alter_table('opportunities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_opportunities_title'))
        batch_op.drop_index(batch_op.f('ix_opportunities_organization'))
        batch_op.drop_index(batch_op.f('ix_opportunities_location'))
        batch_op.drop_index(batch_op.f('ix_opportunities_domain'))
        batch_op.drop_index(batch_op.f('ix_opportunities_category'))

    op.drop_table('opportunities')
    with op.batch_alter_table('interests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_interests_name'))

    op.drop_table('interests')
    # ### end Alembic commands ###
